name: continous integration 
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  Continous-Integration:
    name: Build the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      - name: install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Build the app
        run: npm run build

